# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c3cc6b87eea7c003e16dd9819435d80b1d666511939164a7850ce280500b5d0225c83c277f2bbb1ee9bb1af849f0f08377df2b9c95b0b18ed901fab2d7ae3e

test:
  secret_key_base: 64c6f480af82b4dfe003e4df788658cc527635472fd5e1adb79caa2699e8ac5a9006eb64444b8c24427f08698992124b6be519defa312909a6c5d15a763a03c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
